import { registerCoverageSnapshotSuite } from '../suites/coverage-suite.ts';
import { registerDebuggingSnapshotSuite } from '../suites/debugging-suite.ts';
import { registerDeviceSnapshotSuite } from '../suites/device-suite.ts';
import { registerMacosSnapshotSuite } from '../suites/macos-suite.ts';
import { registerProjectDiscoverySnapshotSuite } from '../suites/project-discovery-suite.ts';
import { registerProjectScaffoldingSnapshotSuite } from '../suites/project-scaffolding-suite.ts';
import { registerSessionManagementSnapshotSuite } from '../suites/session-management-suite.ts';
import { registerSimulatorManagementSnapshotSuite } from '../suites/simulator-management-suite.ts';
import { registerSimulatorSnapshotSuite } from '../suites/simulator-suite.ts';
import { registerSwiftPackageSnapshotSuite } from '../suites/swift-package-suite.ts';
import { registerUiAutomationSnapshotSuite } from '../suites/ui-automation-suite.ts';
import { registerUtilitiesSnapshotSuite } from '../suites/utilities-suite.ts';

registerCoverageSnapshotSuite('json');
registerDebuggingSnapshotSuite('json');
registerDeviceSnapshotSuite('json');
registerMacosSnapshotSuite('json');
registerProjectDiscoverySnapshotSuite('json');
registerProjectScaffoldingSnapshotSuite('json');
registerSessionManagementSnapshotSuite('json');
registerSimulatorManagementSnapshotSuite('json');
registerSimulatorSnapshotSuite('json');
registerSwiftPackageSnapshotSuite('json');
registerUiAutomationSnapshotSuite('json');
registerUtilitiesSnapshotSuite('json');
